# This is a basic workflow to help you get started with Actions

name: LaTeX Validation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Compile the LaTeX document with XeLaTeX
    - name: Build dtx
      uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
          xetex -synctex=1 -interaction=nonstopmode -file-line-error tikz-minesweeper.ins
          xelatex -synctex=1 -interaction=nonstopmode -file-line-error tikz-minesweeper.dtx
          makeindex -s gglo.ist -o tikz-minesweeper.gls tikz-minesweeper.glo
          xelatex -synctex=1 -interaction=nonstopmode -file-line-error tikz-minesweeper.dtx
          xelatex -synctex=1 -interaction=nonstopmode -file-line-error tikz-minesweeper.dtx
        
    # Upload demo to artifacts if the demo is compiled successfully
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: Prebuilt Package
        path: |
          tikz-minesweeper.sty
          tikz-minesweeper.pdf
